// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Models',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Chat',
          items: [
            {
              type: 'autogenerated',
              dirName: 'chat',
            },
          ],
        },
        {
          type: 'category',
          label: 'Embeddings',
          items: [
            {
              type: 'autogenerated',
              dirName: 'embeddings',
            },
          ],
        },
        {
          type: 'category',
          label: 'Moderation',
          items: [
            {
              type: 'autogenerated',
              dirName: 'moderation',
            },
          ],
        },
        {
          type: 'category',
          label: 'Rerank',
          items: [
            {
              type: 'autogenerated',
              dirName: 'rerank',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Judges',
      items: [
        {
          type: 'autogenerated',
          dirName: 'judges',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    'configuration',
    'examples',
    'samples',
    'contribution-guidelines',
  ],
};

export default sidebars;
