site:
  title: Spring AI Watsonx.ai Documentation
  url: https://spring-ai-community.github.io/spring-ai-watsonx-ai
  start_page: spring-ai-watsonx-ai::index.adoc

content:
  sources:
  - url: .
    branches: main
    start_path: docs/src/main/antora

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

asciidoc:
  attributes:
    page-pagination: true
    sectanchors: true
    sectlinks: true
    toc: left
    toclevels: 3
    version-label: Version
