name: Bug Report
description: Report a bug or unexpected behavior in Spring AI Watsonx AI
title: "[Bug]: "
labels: ["waiting-for-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure '...'
        2. Call method '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide details about your environment
      placeholder: |
        - Spring AI Watsonx AI Version: [e.g., 1.0.0]
        - Java Version: [e.g., 17]
        - OS: [e.g., Windows 11, macOS 13, Ubuntu 22.04]
    validations:
      required: true

  - type: textarea
    id: stacktrace
    attributes:
      label: Stack Trace / Error Messages
      description: If applicable, add error messages or stack traces
      placeholder: Paste your error messages or stack traces here...
      render: shell

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      placeholder: |
        ```java
        // Your code here
        ```
      render: java

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)
      placeholder: Any additional information...
