package io.github.springaicommunity.watsonx.chat.message;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.github.springaicommunity.watsonx.chat.message.user.TextChatUserContent;
import io.github.springaicommunity.watsonx.chat.util.Role;
import io.github.springaicommunity.watsonx.chat.util.ToolType;
import java.util.List;

/** Base class for chat messages in a conversation for watsonx.ai. */
public record TextChatMessage(
    @JsonProperty("role") Role role,
    @JsonProperty("content") String content,
    @JsonProperty("name") String name,
    @JsonProperty("content") List<TextChatUserContent> textChatUserContent,
    @JsonProperty("refusal") String refusal,
    @JsonProperty("tool_calls") List<TextChatToolCall> toolCalls,
    @JsonProperty("tool_call_id") String toolCallId) {

  /**
   * Constructor for an assistant message.
   *
   * @param content The content of the message.
   * @param name An optional name for the participant. Provides the model information to
   *     differentiate between participants of the same role.
   * @param refusal An optional refusal message by the assistant.
   * @param toolCalls The tool calls generated by the model, such as function calls.
   */
  public TextChatMessage(
      final String content,
      final String name,
      final String refusal,
      final List<TextChatToolCall> toolCalls) {
    this(Role.ASSISTANT, content, name, null, refusal, toolCalls, null);
  }

  /**
   * Constructor for an assistant message.
   *
   * @param content The content of the message.
   * @param name An optional name for the participant. Provides the model information to
   *     differentiate between participants of the same role.
   */
  public TextChatMessage(final String content, final String name) {
    this(Role.SYSTEM, content, name, null, null, null, null);
  }

  /**
   * Constructor for a tool message.
   *
   * @param content The content of the message.
   * @param name An optional name for the participant. Provides the model information to
   *     differentiate between participants of the same role.
   * @param toolCallId The tool call ID associated with this message.
   */
  public TextChatMessage(final String content, final String name, final String toolCallId) {
    this(Role.TOOL, content, name, null, null, null, toolCallId);
  }

  /**
   * Constructor for a system message.
   *
   * @param content A list of user content for the message.
   * @param name An optional name for the participant. Provides the model information to
   *     differentiate between participants of the same role.
   */
  public TextChatMessage(final List<TextChatUserContent> content, final String name) {
    this(Role.USER, null, name, content, null, null, null);
  }

  public record TextChatToolCall(
      @JsonProperty("id") String id,
      @JsonProperty("type") ToolType type,
      @JsonProperty("function") TextChatFunctionCall function) {}

  public record TextChatFunctionCall(
      @JsonProperty("name") String name, @JsonProperty("arguments") String arguments) {}
}
