spring.main.web-application-type=none
spring.main.banner-mode=off

spring.ai.model.chat=watsonx-ai
spring.ai.model.embedding=none
spring.ai.model.moderation=none

spring.ai.watsonx.ai.api-key=dummy-api-key
spring.ai.watsonx.ai.project-id=dummy-project-id
spring.ai.watsonx.ai.base-url=https://us-south.ml.cloud.ibm.com

spring.ai.watsonx.ai.text-extraction.enabled=false
spring.ai.watsonx.ai.rerank.enabled=false
