spring.main.web-application-type=none
spring.main.banner-mode=off

spring.ai.model.chat=none
spring.ai.model.embedding=none
spring.ai.model.moderation=none

spring.ai.watsonx.ai.text-extraction.enabled=false
spring.ai.watsonx.ai.rerank.enabled=false
